"""Detector implementation for the general-dependence watermark experiments."""

from .refreshing_swz import (
    DEFAULT_OG_ENDPOINT_WEIGHT,
    DEFAULT_SWZ_CAP,
    DetectorResult,
    GrenanderFit,
    Region,
    Report,
    alpha_for_general_fdr_target,
    annotate_reports,
    batch_metrics,
    calibrator_values,
    endpoint_adjusted_grenander_fit,
    fixed_e_factors,
    general_dependence_bound,
    online_grenander_e_factors,
    overlap_tokens,
    path_metrics,
    run_average_from_component_evalues,
    run_average_from_pivots,
    run_online_grenander_from_pivots,
    run_refreshing_from_evalues,
    run_refreshing_from_pivots,
    swz_log_objective,
    swz_optimal_bet,
    threshold_for_general_fdr_target,
)

__all__ = [
    "DEFAULT_OG_ENDPOINT_WEIGHT",
    "DEFAULT_SWZ_CAP",
    "DetectorResult",
    "GrenanderFit",
    "Region",
    "Report",
    "alpha_for_general_fdr_target",
    "annotate_reports",
    "batch_metrics",
    "calibrator_values",
    "endpoint_adjusted_grenander_fit",
    "fixed_e_factors",
    "general_dependence_bound",
    "online_grenander_e_factors",
    "overlap_tokens",
    "path_metrics",
    "run_average_from_component_evalues",
    "run_average_from_pivots",
    "run_online_grenander_from_pivots",
    "run_refreshing_from_evalues",
    "run_refreshing_from_pivots",
    "swz_log_objective",
    "swz_optimal_bet",
    "threshold_for_general_fdr_target",
]
